/****************************************************************************************
  * @filename      : I2ComStringUtil
  * @author        : i2max_my.Seo 
  * @date          : 2021-01-06 오후 3:13
  * @group         : 
  * @group-content : 
  * @description   : 
  * @tester        : I2ComStringUtil_ts.cls
  * @reference     : 
  * @copyright     : Copyright © I2max. All Rights Reserved.
  * @modification Log
  * ===============================================================
  * ver     date                     author              description
  * ===============================================================
    0.1     2021-01-06 오후 3:13     i2max_my.Seo           Create
****************************************************************************************/
public class I2ComStringUtil {
    // TODO : 2021-01-06    Util은 세분화 해서 만든다.
}