/****************************************************************************************
  * @filename      : ZzExmDHConList
  * @author        : I2MAX
  * @date          : 2021-08-09
  * @group         : 
  * @group-content : 
  * @description   : 
  * @tester        : ZzExmDHConList_ts.cls
  * @reference     : 
  * @copyright     : Copyright © I2max. All Rights Reserved.
  * @modification Log
  * ===============================================================
  * ver     date                     author        description
  * ===============================================================
    1.0     2021-08-09          I2MAX.dh           Create
****************************************************************************************/

public with sharing class ZzExmDHConList {

}