/****************************************************************************************
  * @filename      : ZzExmYRAccNewFileQa
  * @author        : I2MAX
  * @date          : 2021-06-10
  * @group         : 
  * @group-content : 
  * @description   : 
  * @tester        : ZzExmYRAccNewFileQa_ts.cls
  * @reference     : 
  * @copyright     : Copyright © I2max. All Rights Reserved.
  * @modification Log
  * ===============================================================
  * ver     date                     author        description
  * ===============================================================
    1.0     2021-05-06          I2MAX.YR           Create
****************************************************************************************/


public with sharing class ZzExmYRAccNewFileQa {

}